server: # REST and WS server
  port: 7000
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "sourceflow"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 3 # Number of pages at 100 each
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO